Update manual
SwedbankPay/swedbank-pay-woocommerce-checkout pull request #140
Opened 2023-01-14 05:45 UTC by olegisk

2023-01-15 07:50 UTC, aait requested changes
In text change the admin portal URL to
  https://admin.payex.com/psp/beta
  and
  admin test portal to
  https://admin.externalintegration.payex.com/psp/beta

2023-01-20 09:28 UTC, aait commented
Replace all instances of https://admin.externalintegration.payex.com/psp/login with https://admin.externalintegration.payex.com/psp/beta 
Replace all instances of https://admin.payex.com/psp/login/ with https://admin.payex.com/psp/beta @olegisk

2023-02-03 00:43 UTC, asbjornu requested changes

2023-02-03 00:43 UTC, asbjornu commented on installation-guide.md
> +To connect your module to the Swedbank Pay system you need to navigate to https://admin.externalintegration.payex.com/psp/beta for test and https://admin.payex.com/psp/beta for production accounts an
```suggestion
To connect your module to the Swedbank Pay system you need to navigate to [Swedbank Pay Merchant Portal (test)](https://merchantportal.externalintegration.swedbankpay.com/) for test and [Swedbank Pay Merchant Portal](https://merchantportal.swedbankpay.com/) for production accounts and generate tokens:
```

2023-02-03 08:21 UTC, asbjornu approved these changes

2023-03-11 09:26 UTC, aait approved these changes

2023-03-11 10:06 UTC, merged