Add option "Make payer optional"
SwedbankPay/swedbank-pay-woocommerce-checkout pull request #21
Opened 2020-07-02 07:17 UTC by aait

2020-07-02 09:25 UTC, asbjornu requested changes

2020-07-02 09:25 UTC, asbjornu commented on includes/class-wc-gateway-swedbank-pay-checkout.php
> +		$this->use_cardholder_info    = isset( $this->settings['use_cardholder_info'] ) ? $this->settings['use_cardholder_info'] : $this->use_cardholder_info;
The `cardHolder` information is always optional and should only be sent if it is available. It doesn't make sense requiring this information, I think.

2020-07-03 20:06 UTC, asbjornu commented on includes/class-wc-gateway-swedbank-pay-checkout.php
> +	public $use_cardholder_info = 'yes';
Does setting `$use_cardholder_info` to  `'yes'` mean that it is required and must always be sent? It should not be required and should only be sent if it is made available by the WooCommerce installation somehow.

2020-07-05 21:03 UTC, asbjornu reviewed
I don't understand what is going to happen when this is merged. Will `cardholder` data still be sent if it is available? Can you please describe in the PR exactly what the intention of the code is and what is supposed to change when this is merged?

2020-07-06 06:54 UTC, closed without merging

2020-07-06 09:19 UTC, asbjornu commented
@aait, @olegisk, why was this closed? Please write your intentions behind pull requests you submit and when they are closed.

2020-07-06 09:33 UTC, aait commented
> @aait, @olegisk, why was this closed? Please write your intentions behind pull requests you submit and when they are closed.

I've close this PR because we got rid of "Send cardholder info" feature, so there is nothing to commit.

2020-07-06 10:23 UTC, asbjornu commented
> I've close this PR because we got rid of "Send cardholder info" feature, so there is nothing to commit.

So now we aren't sending `cardholder` information at all? Or only when available?