WOO-77: Rename Merchant Token to Access Token
SwedbankPay/swedbank-pay-woocommerce-checkout pull request #50
Opened 2020-12-15 11:21 UTC by aait

2020-12-15 11:26 UTC, asbjornu requested changes
The tests aren't running because `uses` and `run` can't be used in the same step. Please fix.

https://github.com/SwedbankPay/swedbank-pay-woocommerce-checkout/blob/457ab848429185830f4d09f7ee8c93d4f0348362/.github/workflows/integration-tests.yml#L39-L46

2020-12-15 11:54 UTC, asbjornu requested changes

2020-12-15 11:54 UTC, asbjornu commented on .github/workflows/integration-tests.yml
>            MERCHANT_TOKEN: ${{ secrets.MERCHANT_TOKEN }}
```suggestion
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
```

2020-12-27 22:44 UTC, asbjornu commented
The tests are failing

2020-12-28 08:30 UTC, aait commented
> The tests are failing

Fixed

2020-12-29 02:06 UTC, asbjornu approved these changes

2020-12-29 06:10 UTC, merged